/**
 * Shared primitives. Every schema in this package is built from these, so a
 * validation rule is defined once and cannot drift between endpoints.
 */

import { z } from 'zod';
import { money, type Money } from './money.js';

/**
 * UUIDv7, generated by the register offline and accepted by the server as
 * given. Version is checked, not just shape: a v4 here means something
 * generated an id with the wrong function, and v4 ids destroy the index
 * locality the schema depends on.
 */
export const uuidV7 = z
  .string()
  .uuid()
  .refine((v) => v[14] === '7', { message: 'must be a UUIDv7 (the register generates these)' });

/** Any UUID, for ids the server issued or that predate the v7 rule. */
export const uuid = z.string().uuid();

/**
 * Money on the wire: a digit string of minor units, parsed to a branded bigint.
 *
 * A JSON number is rejected outright. It would work for every amount anyone
 * tests with and lose precision above 2^53, and more importantly it invites the
 * client to do float arithmetic on a value that must stay exact.
 */
export const moneyMinor = z
  .union([z.string().regex(/^-?\d+$/, 'money must be a whole number of minor units'), z.bigint()])
  .transform((v, ctx): Money => {
    try {
      return money(v);
    } catch (e) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, message: (e as Error).message });
      return z.NEVER;
    }
  });

/** A non-negative amount: prices, totals, tendered cash. */
export const moneyNonNegative = moneyMinor.refine((v) => v >= 0n, 'must not be negative');

/** Fractional cost, `numeric(14,6)`. Stays a string; never becomes a float. */
export const costDecimal = z
  .string()
  .regex(/^-?\d{1,8}(\.\d{1,6})?$/, 'cost allows at most six decimal places');

/**
 * Quantity, `numeric(14,3)`. Three decimals because weighed goods exist, and a
 * string for the same reason cost is one.
 */
export const quantity = z.string().regex(/^-?\d{1,11}(\.\d{1,3})?$/, 'invalid quantity');

/** A tax or discount rate. String, because 0.0825 has no exact float. */
export const rate = z.string().regex(/^\d+(\.\d{1,6})?$/, 'invalid rate');

/** Store and register codes are printed on receipt numbers, so they are short. */
export const storeCode = z.string().regex(/^[A-Z0-9]{1,8}$/, 'A-Z and 0-9, up to 8 characters');
export const registerCode = z.string().regex(/^[A-Z0-9]{1,6}$/, 'A-Z and 0-9, up to 6 characters');

/** URL safe identifier used in paths and category materialized paths. */
export const slug = z
  .string()
  .min(1)
  .max(64)
  .regex(/^[a-z0-9][a-z0-9-]*$/, 'lowercase letters, digits and hyphens');

/**
 * Barcodes are not numbers. Leading zeros are significant, some are 14 digits,
 * and parsing one as an integer is a well known way to make a product
 * unscannable.
 */
export const barcode = z.string().min(4).max(48).regex(/^[0-9A-Za-z._-]+$/);

export const sku = z.string().min(1).max(64).trim();

/** E.164. Stored normalized so a customer lookup by phone actually matches. */
export const phone = z.string().regex(/^\+[1-9]\d{7,14}$/, 'phone must be E.164, e.g. +15125550123');

export const email = z.string().email().max(320).toLowerCase();

/** Server timestamps are ISO 8601 with an offset. Never a naive local time. */
export const timestamp = z.string().datetime({ offset: true });

/**
 * A register's own clock, sent with every upload. The server records its own
 * received_at alongside it and reports on the drift. Device time is evidence,
 * never authority: a register with a wrong clock must not be able to reorder
 * the day's sales.
 */
export const deviceTime = timestamp;

export const entityStatus = z.enum(['active', 'inactive', 'archived']);

/** Cursor pagination. Offset pagination skips rows when the set is changing. */
export const pagination = z.object({
  cursor: z.string().max(256).optional(),
  limit: z.coerce.number().int().min(1).max(200).default(50),
});

export const paginated = <T extends z.ZodTypeAny>(item: T) =>
  z.object({
    data: z.array(item),
    next_cursor: z.string().nullable(),
  });

/**
 * Idempotency key. Every write that moves money or stock carries one, and for
 * register originated writes it is the entity's own UUIDv7, which is what makes
 * a duplicate upload structurally incapable of becoming a duplicate sale.
 */
export const idempotencyKey = z.string().min(8).max(255);

/** The org context. Never taken from the request body: it comes from the token. */
export const orgScope = z.object({ org_id: uuid, store_id: uuid.optional() });

export type Pagination = z.infer<typeof pagination>;
export type EntityStatus = z.infer<typeof entityStatus>;
